version: '3.9'

services:
  api-service:
    container_name: api-container
    build:
      context: ./
      dockerfile: Dockerfile
    image: api-image-sample
    ports:
      - '8080:80'
    networks:
      - backend

  redis:
    image: redis:6.2-alpine
    container_name: redis
    hostname: redis
    ports:
      - '6379:6379'
    environment:
      - ALLOW_EMPTY_PASSWORD=yes
      - REDIS_DISABLE_COMMANDS=FLUSHDB;FLUSHALL
    networks:
      - backend

networks:
  backend:
    driver: bridge