version: '3.9'

services:
  api-service:
    container_name: api-container
    build:
      context: ./
      dockerfile: Dockerfile
    image: api-image-sample
    ports:
      - '8080:80'
    networks:
      - backend

networks:
  backend:
    driver: bridge